<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class ManageMatimonyProfiles extends Model
{
    use HasApiTokens, HasFactory, SoftDeletes, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */

    protected $table = 'm4winreg';

    protected $fillable = [
        'mem_id',
        'MatriID',
        'Prefix',
        'dum_id',
        'franchiseecode',
        'Termsofservice',
        'ConfirmEmail',
        'ConfirmPassword',
        'Profilecreatedby',
        'Referenceby',
        'Name',
        'Gender',
        'DOB',
        'Age',
        'TOB',
        'POB',
        'Maritalstatus',
        'childrenlivingstatus',
        'Education',
        'EducationDetails',
        'Occupation',
        'Employedin',
        'Annualincome',
        'Religion',
        'Caste',
        'Subcaste',
        'Gothram',
        'Language',
        'Star',
        'Moonsign',
        'Horosmatch',
        'Manglik',
        'Height',
        'Weight',
        'BloodGroup',
        'Bodytype',
        'spe_cases',
        'Complexion',
        'Diet',
        'Smoke',
        'Drink',
        'Address',
        'City',
        'Postal',
        'State',
        'Country',
        'Phone',
        'Mobile',
        'mobilecode',
        'Residencystatus',
        'Fathername',
        'Mothersname',
        'Fatherlivingstatus',
        'Motherlivingstatus',
        'Fathersoccupation',
        'Mothersoccupation',
        'Profile',
        'par_profile',
        'Looking',
        'FamilyDetails',
        'Familyvalues',
        'FamilyType',
        'FamilyStatus',
        'FamilyOrigin',
        'noofbrothers',
        'noofsisters',
        'nbm',
        'nsm',
        'PE_FromAge',
        'PE_ToAge',
        'PE_HaveChildren',
        'PE_Height',
        'PE_Complexion',
        'PE_MotherTongue',
        'PartnerExpectations',
        'PE_Religion',
        'PE_Caste',
        'PE_Education',
        'PE_Countrylivingin',
        'PE_Residentstatus',
        'Hobbies',
        'OtherHobbies',
        'Interests',
        'OtherInterests',
        'Status',
        'memtype',
        'Regdate',
        'IP',
        'last_ip',
        'Ref',
        'Agent',
        'DeleteAction',
        'MemshipExpiryDate',
        'expdays',
        'Horoscheck',
        'HorosApprove',
        'PhotoProtect',
        'PhotoprotectPassword',
        'Video',
        'Videocheck',
        'Noofcontacts',
        'photocheck',
        'photochecklist',
        'videochecklist',
        'Horoschecklist',
        'DOBday',
        'DOBmonth',
        'DOByear',
        'Orderstatus',
        'Photo1',
        'Photo1Approve',
        'Photo2',
        'Photo2Approve',
        'Photo3',
        'Photo3Approve',
        'photo_remind_cnt',
        'Logincount',
        'Lastlogin',
        'Thislogin',
        'dumprofile',
        'prosta',
        'pagecount',
        'noyusisters',
        'noyubrothers',
        'matchalertstatus',
        'matchalertsentdate',
        'crop',
        'PE_Height2',
        'quick',
        'r1',
        'r2',
        'r3',
        'r4',
        'r5',
        'r6',
        'r7',
        'r8',
        'r9',
        'r10',
        'r11',
        'r12',
        'a1',
        'a2',
        'a3',
        'a4',
        'a5',
        'a6',
        'a7',
        'a8',
        'a9',
        'a10',
        'a11',
        'a12',
        'thosam',
        'horosother',
        'dummy',
        'dasatype',
        'dasayear',
        'dasamonth',
        'dasadate',
        'featured',
        'ckecheck',
        'fri_email',
        'agt_id',
        'agt_email',
        'verify_email',
        'OnlineUsers',
        'mobileverify',
        'mobileverifycode',
        'appreg',
        'specialcategory',
        'acharyan',
        'mother_tongue'
    ];

    protected $dates = ['deleted_at'];

}
